services:
  - type: web
    name: cocoguard-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./cocoguard.db
      - key: UPLOAD_DIR
        value: ./uploads
      - key: PYTHON_VERSION
        value: 3.11.0
