services:
  - type: web
    name: cocoguard-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./cocoguard.db
      - key: UPLOAD_DIR
        value: ./uploads
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: erwincmartinez.cgc@gmail.com
      - key: SMTP_PASSWORD
        value: loqb qxbh kfki efwd
      - key: SMTP_FROM_EMAIL
        value: erwincmartinez.cgc@gmail.com
      - key: SMTP_FROM_NAME
        value: CocoGuard
      - key: ALLOWED_ORIGINS_RAW
        value: "*"
